#!/bin/bash
md5=`openssl md5 .pio/build/heltec_wifi_lora_32/firmware.bin|sed s/.*=[[:blank:]]//`
version=`cat include/version.h | grep VERSION_NUMBER | sed 's/[^0-9]//g'`
cat > cfg.txt <<- EOM
https://<yourserver>/ota/firmware.bin
${version}
${md5}
1.1
EOM

#scp .pio/build/heltec_wifi_lora_32/firmware.bin <yourserver>:/var/www/html/ota/
#scp cfg.txt <yourserver>:/var/www/html/ota/
