#!/bin/bash
md5=`openssl md5 .pio/build/heltec_wifi_lora_32-release/firmware.bin|sed s/.*=[[:blank:]]//`
version=`cat include/version.h | grep VERSION_NUMBER | sed 's/[^0-9]//g'`
cat > cfg.txt <<- EOM
https://stb.42u.de/ota/firmware.bin
${version}
${md5}
1.1
EOM

scp -4 .pio/build/heltec_wifi_lora_32-release/firmware.bin cfg.txt web:/var/www/html/ota/
